#!/bin/sh

( echo "use std; use serde::{Serialize, Deserialize}; use chrono; use super::flexuuid::FlexUuid; use super::flextimestamp::FlexTimestamp;  use diesel::connection::TransactionManager; use diesel::pg::PgConnection; use diesel::prelude::*; use diesel::sqlite::SqliteConnection; use crate::schema; use schema::*;" && diesel_ext -d "Queryable, Insertable, Serialize, Deserialize, Debug, Clone, Default, PartialEq" --model ) | sed \
        -e 's/UUID: Option<String>/UUID: Option<FlexUuid>/g' \
        -e 's/UUID: String/UUID: FlexUuid/g' \
        -e 's/t: Option<NaiveDateTime>/t: Option<FlexTimestamp>/g' \
        -e 's/t: NaiveDateTime/t: FlexTimestamp/g' \
        -e 's/pub struct \([A-Za-z][A-Za-z]*\)/#[table_name = "\1s"]\n#[serde(default)]\n&/g' \
        -e 's/imestamp: NaiveDateTime/imestamp: FlexTimestamp/g' \
        -e 's/, Identifiable//g' \
| grep -v 'primary_key' | grep -v 'allow'



